### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by tmcdo1** [tmcdo1/tmcdo1.github.io#1]
- [x] Add command for loading domains instead of searching
- [x] Add Amazon.com to the common icons
- [x] Add changing gradient backgrounds based off of weather (grey and white for cloudy, etc)
- [x] Add commands for searching using different engines (duckduckgo, bing, youtube, amazon, etc)
- [ ] Try to add bar for favorited sites
- [x] Add mobile support
